default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .static
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/applications/hello/templates/
    - src/applications/landing/templates/
    - src/applications/blog/templates/
    - src/project/templates/
  MODE_DEBUG: true
  HOST: ""
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: "My37"
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2

heroku:
  HOST: "My37.herokuapp.com"
  MODE_DEBUG: false
